*;
* IMPUTE VARIABLE: YOJ;
*;
label IMP_YOJ = 'Imputed YOJ';
IMP_YOJ = YOJ;
IF missing(YOJ) THEN DO;
_random_ = DMRAN(12345);
if _random_ <= 0.01 then IMP_YOJ = 0;
else if _random_ <= 0.1 then IMP_YOJ = 0;
else if _random_ <= 0.10 then IMP_YOJ = 1;
else if _random_ <= 0.20 then IMP_YOJ = 2;
else if _random_ <= 0.25 then IMP_YOJ = 3;
else if _random_ <= 0.30 then IMP_YOJ = 4;
else if _random_ <= 0.40 then IMP_YOJ = 5;
else if _random_ <= 0.50 then IMP_YOJ = 7;
else if _random_ <= 0.60 then IMP_YOJ = 9;
else if _random_ <= 0.75 then IMP_YOJ = 13;
else if _random_ <= 0.80 then IMP_YOJ = 15;
else if _random_ <= 0.90 then IMP_YOJ = 21;
else if _random_ <= 0.99 then IMP_YOJ = 30;
else IMP_YOJ = 41;
END;
